DROP TABLE IF EXISTS TB_ItemVenda;
DROP TABLE IF EXISTS TB_Venda;
DROP TABLE IF EXISTS TB_Login;
DROP TABLE IF EXISTS TB_NivelAcesso;
DROP TABLE IF EXISTS TB_Funcionario;
DROP TABLE IF EXISTS TB_Cidade;
DROP TABLE IF EXISTS TB_UF;
DROP TABLE IF EXISTS TB_MovimentacaoEstoque;
DROP TABLE IF EXISTS TB_Estoque;
DROP TABLE IF EXISTS TB_Produto;
DROP TABLE IF EXISTS TB_Marca;
DROP TABLE IF EXISTS TB_Categoria;
DROP TABLE IF EXISTS TB_Subcategoria;
DROP TABLE IF EXISTS TB_Sabor;
GO